### ISSUE TITLE
index.Rmd to index.qmd?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [djnavarro/quarto-blog#1]
https://github.com/djnavarro/quarto-blog/blob/d6ba65e158d596e63dd8518d8d69ec2335eaf6eb/posts/2022-04-20_porting-to-quarto/index.qmd#L231

I think it should say so on this line?

Great post as always, thanks for writing it up!

**Comment by djnavarro** [comment]
oops thanks for catching that!
