### ISSUE TITLE
RSS feed error in the blog -  XML Parsing Error: not well-formed

### ISSUE THREAD

**Issue by fortunewalla** [djnavarro/quarto-blog#51]
Hi, I tried to view the RSS feed of your blog. It showed the following error.

Is it only at my end?

```
XML Parsing Error: not well-formed
Location: https://blog.djnavarro.net/index.xml
Line Number 5189, Column 12:
<pre><code></code></pre>
-----------^
```

**Comment by djnavarro** [comment]
Very belated thank you for opening this. It's been on my to-do list for ages. The problem was at my end. Took me a while to get it done, but with any luck the RSS works again!
